{% set name = "cameralink-gateway" %}
{% set version = "7.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: b470de178b0e46cdf71463cd7d18088aed7d9129bed06976a5f0a1aa717190fe

build:
  skip: True  # [win or osx]
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/cameralink-gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cameralink-gateway software and firmware'
  description: |
    firmware for cameralink-gateway devices.
  doc_url: https://github.com/slaclab/cameralink-gateway
  dev_url: https://github.com/slaclab/cameralink-gateway

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

